### ISSUE TITLE
trained_resnet_model_v2_10.tflite AI/ML Model Updates for Saral v1.0

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#32]
trained_resnet_model_v2_10.tflite support:

Below exception thrown when trying to use v2_10.tflite in the app.

2021-11-18 16:20:24.337 4708-13961/? W/ExynosCameraSec: [CAM(0)][Back_0]-(m_getSensorListenerData[31474]):skip the Rotation data. ret -11
2021-11-18 16:20:24.343 3452-3452/com.saralapp W/System.err: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
2021-11-18 16:20:24.343 4688-4688/? D/gralloc: [mali_gralloc_allocate] begin
2021-11-18 16:20:24.343 4688-4688/? D/gralloc: buffer_descriptor: wh(2131 1017) usage_pc(0x966 0x906) hal_format(0x4) layer_count(1) sizes(0 0 0) strde(0) byte_stride(0) alloc_wh(0 0) internal_format(0x0) alloc_format(0x0) fd_count(1) plane_count(0)
2021-11-18 16:20:24.344 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzpf.zza(com.google.firebase:firebase-ml-common@@22.0.1:38)
2021-11-18 16:20:24.344 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzpe.run(Unknown Source:4)
2021-11-18 16:20:24.344 3452-3452/com.saralapp W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-11-18 16:20:24.345 3452-3452/com.saralapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-11-18 16:20:24.345 4688-4688/? D/gralloc: [mali_gralloc_allocate] allocation successful
2021-11-18 16:20:24.345 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zze.dispatchMessage(com.google.firebase:firebase-ml-common@@22.0.1:6)
2021-11-18 16:20:24.345 3452-3452/com.saralapp W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-11-18 16:20:24.345 3452-3452/com.saralapp W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2021-11-18 16:20:24.346 3452-3452/com.saralapp W/System.err: Caused by: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 11] and a Java object with shape [1, 10].
2021-11-18 16:20:24.346 5086-7449/? I/EDMNativeHelperService: isCameraEnabled
2021-11-18 16:20:24.347 3452-3452/com.saralapp W/System.err:     at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:242)
2021-11-18 16:20:24.347 5086-7449/? D/EDMNativeHelper: isCameraEnabled
2021-11-18 16:20:24.347 3452-3452/com.saralapp W/System.err:     at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
2021-11-18 16:20:24.347 3452-3452/com.saralapp W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:157)
2021-11-18 16:20:24.347 3452-3452/com.saralapp W/System.err:     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:250)
2021-11-18 16:20:24.348 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzqw.runForMultipleInputsOutputs(com.google.firebase:firebase-ml-model-interpreter@@22.0.1:4)
2021-11-18 16:20:24.348 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzqo.zza(com.google.firebase:firebase-ml-model-interpreter@@22.0.1:85)
2021-11-18 16:20:24.348 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzqo.zza(com.google.firebase:firebase-ml-model-interpreter@@22.0.1:147)
2021-11-18 16:20:24.348 5086-7449/? D/EDMNativeHelper: checking for camera in EnterpriseDeviceManagerService
2021-11-18 16:20:24.348 5086-7449/? D/EnterpriseDeviceManagerService: isCameraEnabledNative
2021-11-18 16:20:24.349 5086-7449/? D/EnterpriseDeviceManagerService: checking for camera in restriction policy
2021-11-18 16:20:24.349 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzpj.zza(com.google.firebase:firebase-ml-common@@22.0.1:31)
2021-11-18 16:20:24.349 5086-7449/? D/RestrictionPolicy: isCameraEnabled ret(true) userId(0) cxtInfo.mCallerUid(10499) cxtInfo.mContainerId(0)
2021-11-18 16:20:24.349 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzpl.call(Unknown Source:8)
2021-11-18 16:20:24.349 3452-3452/com.saralapp W/System.err:     at com.google.android.gms.internal.firebase_ml.zzpf.zza(com.google.firebase:firebase-ml-common@@22.0.1:32)
2021-11-18 16:20:24.349 3452-3452/com.saralapp W/System.err: 	... 6 more
2021-11-18 16:20:24.349 3452-3452/com.saralapp E/SrlSDK::HWClassify: Internal error has occurred when executing Firebase ML tasks

**Comment by dileep-gadiraju** [comment]
Testing in progress with Handwritten Digits TFLite model v2.10 in the below branch:
https://github.com/Sunbird-Saral/Project-Saral/tree/feature/adopt-tflite-v2_10

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 , you certified this already please add your test results and close this enhancement.

**Comment by apurvabisht97** [comment]
new model is working as expected .
